-- Relates to the "Assign Job Title" UI.
-- Trigger to log job title changes.

-- create the job_title_changes table
CREATE TABLE job_title_changes (
    change_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INT,
    old_title_id INT,
    new_title_id INT,
    change_date DATE
);

--trigger to log job title changes
CREATE OR REPLACE TRIGGER trg_job_title_update
BEFORE UPDATE OF title_id ON employees
FOR EACH ROW
BEGIN
    INSERT INTO job_title_changes (employee_id, old_title_id, new_title_id, change_date)
    VALUES (:OLD.employee_id, :OLD.title_id, :NEW.title_id, SYSDATE);
END;
/

-- update to show the trigger
UPDATE employees SET title_id = 3 WHERE employee_id = 1;

--display the changes to verify if the trigger worked
SET SERVEROUTPUT ON;
DECLARE
    v_employee_id INT := 1; 
BEGIN
    FOR rec IN (SELECT * FROM job_title_changes WHERE employee_id = v_employee_id) LOOP
        DBMS_OUTPUT.PUT_LINE('Change ID: ' || rec.change_id || 
                             ', Employee ID: ' || rec.employee_id || 
                             ', Old Title ID: ' || rec.old_title_id || 
                             ', New Title ID: ' || rec.new_title_id || 
                             ', Change Date: ' || TO_CHAR(rec.change_date, 'DD-MON-YYYY HH24:MI:SS'));
    END LOOP;
END;
/